> # TIL- 자바프로그래밍 입문강좌 04 - 2021-04-11

## 💡 에러와 예외

<hr/>

- 프로그램에 문제가 있는 것을 말한다.
- 예외로 인해 시스템 동작이 멈추는것을 방지 하는 것이 예외처리.

> Exception : 개발자가 대처할 수 있음.

> Error: 개발자가 대처할 수 없음. -> 기계적 오류 등
> </br>

> 자주 발생하는 Exception

- FileNotFoundException

  - 존재하지 않는 파일을 열려고 시도 할때 발생하는 예외

- ArithmeticException

  - 0으로 나누려 하는 경우에 발생하는 예외

- ArrayIndexOutOfBoundsException
  - 배열보다 큰 인덱스를 참조하려 할때 발생하는 예외

</br>
</br>

## 💡 예외처리

</br>
<hr/>

### 💫 Try Catch문 -> 가장 많이 사용됨.

```java
try {
    ...
} catch(예외1) {
    ...
} catch(예외2) {
    ...
...
}
```

- try문안의 수행할 문장들에서 예외가 발생하지 않는다면 catch문 다음의 문장들은 수행이 되지 않는다. 하지만 try문안의 문장들을 수행 중 해당 예외가 발생하면 예외에 해당되는 catch문이 수행된다.

```java
int c;
try {
    c = 4 / 0;
}catch(ArithmeticException e) {
    c = -1;
}

// 0으로 나눌 경우 ArithmeticException가 발생하는데 이럴경우 catch하여 c = -1;를 대입하도록 예외처리
```

</br>
<hr/>

### 💫 Finally

프로그램 수행 도중 예외가 발생하면 프로그램이 중지되거나 예외처리되어 실행된다. </br>
하지만 어떤 예외가 와도 `반드시 실행되어야 하는` 부분이 있다면 Finally를 사용한다.

```java
public class Test {
    public void shouldBeRun() {
        System.out.println("ok thanks.");
    }

    public static void main(String[] args) {
        Test test = new Test();
        int c;
        try {
            c = 4 / 0;
            test.shouldBeRun();
        } catch (ArithmeticException e) {
            c = -1;
        }
    }
}
// shouldBeRun() 메소드는 절대로 실행되지 않을 것이다.
// c = 4 / 0; 여기서 에러처리가 되어버리기 때문이다.
//히지만 반드시 shouldBeRun()를 수행함으로써 "ok, thanks"가 출력되기를 원한다면

```

</br>

```java
public class Test {
    public void shouldBeRun() {
        System.out.println("ok thanks.");
    }

    public static void main(String[] args) {
        Test test = new Test();
        int c;
        try {
            c = 4 / 0;
        } catch (ArithmeticException e) {
            c = -1;
        } finally {
            test.shouldBeRun();
        }
    }
}
```

- finally구문은 예외발생 여부에 상관없이 무조건 실행된다.
- 따라서 "ok, thanks"라는 문장이 출력될 것이다.

</br>
<hr/>

### 💫 throws

- 예외 발생 시 예외를 직접 처리하지 않고 호출한 곳으로 넘긴다.

```java

public class MClass004{

	public static void main(String[] args){
		MClass004 mainClass004 = new MClass004();

		try{
			mainClass004.firstMethod();
		}catch(Exception e){
			e.print("에러!")
		}
	}

	public void firstMethod() throws Exception{
		secondMethod();
	}

	public void secondMethod() throws Exception{
		thirdMethod();
	}

	public void thirdMethod() throws Exception{
		System.out.println(10/0);
	}
}
```

    위 코드는 반드시 에러가 난다. 10/0 이기 때문!</br> 최초 firstMethod를 부르고 firstMethod는 secondMethod를 부른다.</br>
    다시 secondMethod는 thirdMethod를 부르는데
    thirdMethod에서 에러가난다. </br> 하지만 throws Exception를 통해 thirdMethod를 호출한 secondMethod에게 에러를 넘긴다. </br> secondMethod와 firstMethod 도 throws이기 때문에 결국  firstMethod를 불렀던 메인에서 처리하게 된다.

</br>
</br>
</br>
</br>

## 💡 입력과 출력

<hr/>

- 다른 곳의 데이터를 가져오는 것을 입력이라 하고, 다른 곳으로 데이터를 내보내는 것을 출력이라 한다.

- 데이터가 오가는 통로, 단위를 스트림 이라고 한다.

> 기본적으로 Scanner와 System.out.println을 통해 입출력을 수행할수 있으며</br>
> java.io 패키지의 BufferedReader와 BufferedWriter 클래스로 더 빠른 입출력이 가능하다.

</br>
<hr/>

### 💫 FileInputStream, FileOutputStream

</br>

- FileInputStream => read() _1바이트 씩 읽어 온다_
- FileInputStream => write()

</br>
<hr/>

### 💫 Scanner

</br>

java.util 패키지의 Scanner 클래스.

```java

import java.util.Scanner; //임포트 필수!

public class Main {
  public static void main(String args[]) {
    //Scanner 클래스 객체 생성
    Scanner scan = new Scanner(System.in);
    //라인 단위로 입력 데이터를 받는다. (입력하고 엔터 친 데이터까지)
    String inputStr = scan.nextLine();
  }
}
```

</br>
</br>
</br>
</br>

## 💡 네트워크

</br>
<hr/>

### 💫 소켓

</br>

- 네트워크 상에서 데이터를 주고 받기 위한 장치
